# Generated by Django 3.2.9 on 2021-12-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211214_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
    ]
