# Generated by Django 3.2.9 on 2021-12-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_fake'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.IntegerField(default=0),
        ),
    ]
