# Generated by Django 2.2.5 on 2021-11-12 08:58

import DhametCode.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(blank=True, default=DhametCode.models.generate_game_code, max_length=10, null=True)),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('State', models.CharField(default='wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww_bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb', max_length=81)),
                ('player1', models.CharField(max_length=200)),
                ('player2', models.CharField(max_length=200)),
                ('Current', models.IntegerField(default=0)),
                ('Length', models.IntegerField(default=0)),
                ('Moves', models.TextField(default='', max_length=10000)),
                ('last_move', models.CharField(default='', max_length=100, null=True)),
                ('Ongoing', models.BooleanField(default=False)),
                ('Winner', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Image', models.ImageField(null=True, upload_to='images')),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Elo', models.IntegerField(default=0)),
            ],
        ),
    ]
