# Generated by Django 2.2.5 on 2021-11-11 16:25

import DhametCode.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DhametCode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Code',
            field=models.CharField(default=DhametCode.models.generate_game_code, max_length=10, null=True, unique=True),
        ),
    ]
