# Generated by Django 3.2.9 on 2022-01-31 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DhametCode', '0003_alter_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='timer_creator',
            field=models.TimeField(blank=True, default=datetime.time(0, 35), null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='timer_opponent',
            field=models.TimeField(blank=True, default=datetime.time(0, 35), null=True),
        ),
    ]
