# Generated by Django 2.2.5 on 2021-11-12 11:25

import DhametCode.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DhametCode', '0003_auto_20211112_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Code',
            field=models.CharField(blank=True, default=DhametCode.models.generate_game_code, max_length=100, null=True),
        ),
    ]
