# Generated by Django 3.2.9 on 2022-01-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DhametCode', '0004_auto_20220131_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='timer_creator',
            field=models.IntegerField(blank=True, default=600, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='timer_opponent',
            field=models.IntegerField(blank=True, default=600, null=True),
        ),
    ]
