# Generated by Django 3.2.9 on 2022-02-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DhametCode', '0006_auto_20220131_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='creator_time',
            field=models.IntegerField(default=600),
        ),
    ]
