# Generated by Django 3.2.9 on 2022-02-01 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DhametCode', '0007_alter_game_creator_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_move_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
