# Generated by Django 3.2.12 on 2022-02-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DhametCode', '0009_alter_game_last_move_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='creator_time',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='game',
            name='opponent_time',
            field=models.IntegerField(blank=True, default=300, null=True),
        ),
    ]
